-- ============================================================
-- DXTR Seed SQL  (multi-game, 14 days history)
-- Run in Supabase Dashboard > SQL Editor
-- ============================================================

-- Clinician
INSERT INTO "Clinician" (id, name) VALUES ('dr-tabish', 'Dr. Tabish') ON CONFLICT (id) DO NOTHING;

-- Patients
INSERT INTO "Patient" (id, name) VALUES ('edwin-001', 'Edwin') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Patient" (id, name) VALUES ('giles-001', 'Giles') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Patient" (id, name) VALUES ('agatha-001', 'Agatha') ON CONFLICT (id) DO NOTHING;
INSERT INTO "Patient" (id, name) VALUES ('demo-live-001', 'Demo Patient') ON CONFLICT (id) DO NOTHING;

-- Assignments
INSERT INTO "Assignment" (id, "clinicianId", "patientId") SELECT gen_random_uuid()::text, 'dr-tabish', 'edwin-001' WHERE NOT EXISTS (SELECT 1 FROM "Assignment" WHERE "clinicianId"='dr-tabish' AND "patientId"='edwin-001');
INSERT INTO "Assignment" (id, "clinicianId", "patientId") SELECT gen_random_uuid()::text, 'dr-tabish', 'giles-001' WHERE NOT EXISTS (SELECT 1 FROM "Assignment" WHERE "clinicianId"='dr-tabish' AND "patientId"='giles-001');
INSERT INTO "Assignment" (id, "clinicianId", "patientId") SELECT gen_random_uuid()::text, 'dr-tabish', 'agatha-001' WHERE NOT EXISTS (SELECT 1 FROM "Assignment" WHERE "clinicianId"='dr-tabish' AND "patientId"='agatha-001');
INSERT INTO "Assignment" (id, "clinicianId", "patientId") SELECT gen_random_uuid()::text, 'dr-tabish', 'demo-live-001' WHERE NOT EXISTS (SELECT 1 FROM "Assignment" WHERE "clinicianId"='dr-tabish' AND "patientId"='demo-live-001');

-- GameConfigs
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'car-racer', 'gyroscope', '{"targetPronation":15,"targetSupination":15,"deadZone":5}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='car-racer');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'car-racer', 'gyroscope', '{"targetPronation":15,"targetSupination":15,"deadZone":5}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='car-racer');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'car-racer', 'gyroscope', '{"targetPronation":15,"targetSupination":15,"deadZone":5}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='car-racer');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'car-racer', 'gyroscope', '{"targetPronation":15,"targetSupination":15,"deadZone":5}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='car-racer');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'alien-abduction', 'fsr', '{"threshold":1200,"holdTimeMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='alien-abduction');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'alien-abduction', 'fsr', '{"threshold":1200,"holdTimeMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='alien-abduction');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'alien-abduction', 'fsr', '{"threshold":1200,"holdTimeMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='alien-abduction');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'alien-abduction', 'fsr', '{"threshold":1200,"holdTimeMs":500}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='alien-abduction');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'fossil-finder', 'imu', '{"targetDeviation":12,"deadZone":3}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='fossil-finder');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'fossil-finder', 'imu', '{"targetDeviation":12,"deadZone":3}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='fossil-finder');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'fossil-finder', 'imu', '{"targetDeviation":12,"deadZone":3}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='fossil-finder');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'fossil-finder', 'imu', '{"targetDeviation":12,"deadZone":3}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='fossil-finder');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'storm-witch', 'fsr', '{"threshold":800,"holdTimeMs":400}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='storm-witch');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'storm-witch', 'fsr', '{"threshold":800,"holdTimeMs":400}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='storm-witch');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'storm-witch', 'fsr', '{"threshold":800,"holdTimeMs":400}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='storm-witch');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'storm-witch', 'fsr', '{"threshold":800,"holdTimeMs":400}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='storm-witch');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'fly-swatter', 'ultrasonic', '{"triggerDistance":10,"cooldownMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='fly-swatter');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'fly-swatter', 'ultrasonic', '{"triggerDistance":10,"cooldownMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='fly-swatter');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'fly-swatter', 'ultrasonic', '{"triggerDistance":10,"cooldownMs":500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='fly-swatter');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'fly-swatter', 'ultrasonic', '{"triggerDistance":10,"cooldownMs":500}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='fly-swatter');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'edwin-001', 'rhythm-rehab', 'imu', '{"pitchThreshold":15,"reactionWindowMs":1500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='edwin-001' AND "gameId"='rhythm-rehab');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'giles-001', 'rhythm-rehab', 'imu', '{"pitchThreshold":15,"reactionWindowMs":1500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='giles-001' AND "gameId"='rhythm-rehab');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'agatha-001', 'rhythm-rehab', 'imu', '{"pitchThreshold":15,"reactionWindowMs":1500}', true, 3, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='agatha-001' AND "gameId"='rhythm-rehab');
INSERT INTO "GameConfig" (id, "patientId", "gameId", "inputType", "difficultyParams", "calibrationComplete", "calibrationSetsCompleted", "autoProgressionEnabled") SELECT gen_random_uuid()::text, 'demo-live-001', 'rhythm-rehab', 'imu', '{"pitchThreshold":15,"reactionWindowMs":1500}', false, 0, true WHERE NOT EXISTS (SELECT 1 FROM "GameConfig" WHERE "patientId"='demo-live-001' AND "gameId"='rhythm-rehab');

-- ============================================================
-- Historical DailyProgress, GameSet, RepResult
-- ============================================================

-- ── Edwin ──