[env:esp32thing_plus]
platform = espressif32
board = esp32thing_plus
framework = arduino
lib_deps =
    sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@1.2.11
monitor_speed = 115200
build_flags = -DICM_20948_USE_DMP
